In [33]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [9]:

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [21]:
X = df.drop('sepal width (cm)', axis = 1)
y = iris.target

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40)

In [23]:
X_train

sepal length (cm)  petal length (cm)  petal width (cm)
62                6.0                4.0               1.0
23                5.1                1.7               0.5
26                5.0                1.6               0.4
48                5.3                1.5               0.2
2                 4.7                1.3               0.2
..                ...                ...               ...
71                6.1                4.0               1.3
12                4.8                1.4               0.1
50                7.0                4.7               1.4
7                 5.0                1.5               0.2
70                5.9                4.8               1.8

[120 rows x 3 columns]

In [27]:
X_test

sepal length (cm)  petal length (cm)  petal width (cm)
38                 4.4                1.3               0.2
66                 5.6                4.5               1.5
115                6.4                5.3               2.3
117                7.7                6.7               2.2
89                 5.5                4.0               1.3
136                6.3                5.6               2.4
68                 6.2                4.5               1.5
94                 5.6                4.2               1.3
84                 5.4                4.5               1.5
28                 5.2                1.4               0.2
90                 5.5                4.4               1.2
11                 4.8                1.6               0.2
40                 5.0                1.3               0.3
126                6.2                4.8               1.8
79                 5.7                3.5               1.0
144                6.7                5.7               2.5
123                6.3                4.9               1.8
124                6.7                5.7               2.1
76                 6.8                4.8               1.4
59                 5.2                3.9               1.4
132                6.4                5.6               2.2
105                7.6                6.6               2.1
53                 5.5                4.0               1.3
17                 5.1                1.4               0.3
64                 5.6                3.6               1.3
18                 5.7                1.7               0.3
13                 4.3                1.1               0.1
116                6.5                5.5               1.8
9                  4.9                1.5               0.1
81                 5.5                3.7               1.0

In [25]:
y_train

array([1, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 1, 2, 2, 2, 0, 2, 2, 1, 0, 2, 1,
       1, 1, 0, 0, 1, 1, 2, 2, 0, 2, 1, 0, 2, 0, 0, 2, 0, 2, 2, 0, 2, 1,
       0, 0, 2, 0, 2, 2, 1, 1, 2, 1, 2, 0, 2, 1, 1, 0, 0, 0, 2, 2, 1, 0,
       1, 2, 2, 1, 2, 2, 1, 1, 0, 1, 1, 2, 1, 2, 0, 2, 2, 1, 1, 0, 2, 1,
       0, 1, 2, 0, 0, 2, 1, 0, 0, 1, 0, 2, 1, 2, 0, 2, 1, 0, 0, 2, 0, 1,
       1, 1, 1, 0, 2, 1, 0, 1, 0, 1])

In [26]:
y_test

array([0, 1, 2, 2, 1, 2, 1, 1, 1, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1, 1, 2, 2,
       1, 0, 1, 0, 0, 2, 0, 1])

In [28]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [29]:
X_train_scaled

array([[ 0.17933237,  0.15787661, -0.23382732],
       [-0.90875166, -1.13896696, -0.89249581],
       [-1.02964989, -1.19535147, -1.02422951],
       [-0.66695521, -1.25173597, -1.28769691],
       [-1.39234456, -1.36450498, -1.28769691],
       [ 0.66292527,  1.06002866,  1.21524337],
       [-1.51324279, -1.30812047, -1.15596321],
       [-1.75503924, -1.36450498, -1.28769691],
       [-0.18336231,  0.72172164,  1.08350967],
       [-0.18336231, -1.25173597, -1.02422951],
       [-1.51324279, -1.25173597, -1.28769691],
       [ 1.02561995,  0.55256813,  0.42484118],
       [ 0.30023059,  0.66533714,  0.82004227],
       [ 1.50921285,  1.22918217,  1.21524337],
       [ 1.63011107,  1.28556667,  0.82004227],
       [-0.90875166, -1.25173597, -1.28769691],
       [ 2.2346022 ,  1.7930272 ,  1.47871077],
       [ 0.17933237,  0.60895263,  0.82004227],
       [ 0.90472172,  0.38341462,  0.29310748],
       [-1.15054811, -1.30812047, -1.4194306 ],
       [ 0.54202704,  1.28556667,  1.742

In [30]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=3)

In [34]:

y_pred = knn.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 1.0

Confusion Matrix:
 [[ 8  0  0]
 [ 0 12  0]
 [ 0  0 10]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00        12
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

